Repository Bravos-Team/SteakPlatform-Frontend, pull requests merged in 2025-04, with the labels that each got.

#9 #8 Configuration project, add TailwindCss into project and demo Native Css Variables
  FIX.md
  package.json
  postcss.config.js
  src/App.vue
  src/assets/config/tailwind.css
  src/assets/css/auth/layout.css
  src/assets/variables/auth/_variables.css
  src/main.js
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: configure

#10 Merging Develop to Master
  FIX.md
  RULE.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  src/App.vue
  src/assets/config/tailwind.css
  src/assets/css/auth/layout.css
  src/assets/css/auth/login.css
  src/assets/favicon.ico
  src/assets/images/auth/down-line.svg
  src/assets/images/auth/eyes-off.svg
  src/assets/images/auth/icon-language.svg
  src/assets/images/auth/logo-google.svg
  src/assets/images/auth/logo-on.svg
  src/assets/images/auth/logo_steak.svg
  src/assets/images/auth/logos_facebook.svg
  src/assets/variables/auth/_variables.css
  src/components/auth/Layout.vue
  src/components/auth/LoginForm.vue
  src/components/tests/Test.vue
  src/main.js
  src/router/index.js
  src/services/api.js
  src/views/auth/LoginPage.vue
  src/views/store/base.vue
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: feature

#11 #4 - finish UI Login
  src/components/auth/LoginForm.vue
  src/layouts/auth/AuthLayout.vue
  src/layouts/auth/Headers.vue
  src/router/index.js
  src/views/auth/LoginPage.vue
Labels: feature

#13 #12 - updated new RULE for working with TailWindCss
  RULE.md
Labels: documentation

#15 #14 - Updated RULE - talk about Optimize Css Coding
  RULE.md
  src/App.vue
Labels: documentation

#26 #1 - Coding Registration UI , fix 1 so cau truc project
  src/components/auth/HeaderBase.vue
  src/components/auth/LoginForm.vue
  src/components/store/FooterStore.vue
  src/components/store/HeaderStore.vue
  src/layouts/store/StoreLayout.vue
  src/router/index.js
  src/views/auth/LoginPage.vue
  src/views/auth/RegistrationPage.vue
  src/views/store/HomePage.vue
  src/views/store/base.vue
Labels: feature

#28 #27 - fix project structures - responsive UI
  src/assets/svgs/auth/tick-svgrepo-com.svg
  src/components/auth/HeaderAuth.vue
  src/components/auth/LoginForm.vue
  src/layouts/auth/AuthLayout.vue
  src/layouts/store/StoreLayout.vue
  src/router/index.js
  src/views/auth/RegistrationPage.vue
Labels: fixing

#34 #33 - Updated UI/component registry related, add vite-svg-loader to work with svg file
  index.html
  package-lock.json
  package.json
  src/assets/images/auth/logo_steak.svg
  src/components/auth/LoginForm.vue
  src/router/index.js
  src/views/auth/EmailAuthenticationRequirement.vue
  src/views/auth/RegistrationPage.vue
  vite.config.js
  yarn.lock
Labels: feature

#39 Merging - new updated UI login, registry, VerifyEmail with tailwindCss
  index.html
  package-lock.json
  package.json
  src/assets/config/tailwind.css
  src/assets/favicon.ico
  src/assets/images/auth/down-line.svg
  src/assets/images/auth/eyes-off.svg
  src/assets/images/auth/icon-language.svg
  src/assets/images/auth/khong_co_gi.md
  src/assets/images/auth/logo-google.svg
  src/assets/images/auth/logo-on.svg
  src/assets/images/auth/logo_steak.svg
  src/assets/images/auth/logos_facebook.svg
  src/components/auth/HeaderAuth.vue
  src/components/auth/HeaderBase.vue
  src/components/auth/LoginForm.vue
  src/components/store/FooterStore.vue
  src/layouts/auth/AuthLayout.vue
  src/layouts/store/StoreLayout.vue
  src/router/index.js
  src/views/auth/EmailAuthenticationRequirement.vue
  src/views/auth/LoginPage.vue
  src/views/auth/RegistrationPage.vue
  src/views/store/HomePage.vue
  src/views/store/base.vue
  tailwind.config.js
  yarn.lock
Labels: merging

#44 #32 - Create StoreHomePage UI and create some commons components for Game UI
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/config/tailwind.css
  src/components/auth/HeaderAuth.vue
  src/components/common/CategoryBaseBar.vue
  src/components/common/CollaboratorsBar.vue
  src/components/common/FreeGameBar.vue
  src/components/home/HomeHeader.vue
  src/components/store/CollaborationCard.vue
  src/components/store/GameCard.vue
  src/components/store/GameCardHorizontal.vue
  src/components/store/StoreSearchingBar.vue
  src/components/store/StoreSliders.vue
  src/components/store/StoreTopBar.vue
  src/layouts/home/HomeLayout.vue
  src/layouts/store/StoreLayout.vue
  src/main.ts
  src/router/index.ts
  src/services/common/CurrencyUtils.ts
  src/views/auth/LoginPage.vue
  src/views/auth/RegistrationPage.vue
  src/views/home/HomePage.vue
  src/views/store/HomePage.vue
  src/views/store/StoreHomePage.vue
  tsconfig.json
  yarn.lock
Labels: feature
